INSERT INTO tag (id, tag_key, kor_name, created_at, updated_at)
VALUES (1, 'math', '수학', NOW(), NOW()),
       (2, 'implementation', '구현', NOW(), NOW()),
       (3, 'dp', '다이나믹 프로그래밍', NOW(), NOW()),
       (4, 'graphs', '그래프 이론', NOW(), NOW()),
       (5, 'data_structures', '자료 구조', NOW(), NOW()),
       (6, 'greedy', '그리디 알고리즘', NOW(), NOW()),
       (7, 'string', '문자열', NOW(), NOW()),
       (8, 'bruteforcing', '브루트포스 알고리즘', NOW(), NOW()),
       (9, 'graph_traversal', '그래프 탐색', NOW(), NOW()),
       (10, 'sorting', '정렬', NOW(), NOW()),
       (11, 'ad_hoc', '애드 혹', NOW(), NOW()),
       (12, 'geometry', '기하학', NOW(), NOW()),
       (13, 'trees', '트리', NOW(), NOW()),
       (14, 'number_theory', '정수론', NOW(), NOW()),
       (15, 'segtree', '세그먼트 트리', NOW(), NOW()),
       (16, 'binary_search', '이분 탐색', NOW(), NOW()),
       (17, 'set', '집합과 맵', NOW(), NOW()),
       (18, 'constructive', '해 구성하기', NOW(), NOW()),
       (19, 'simulation', '시뮬레이션', NOW(), NOW()),
       (20, 'arithmetic', '사칙연산', NOW(), NOW()),
       (21, 'prefix_sum', '누적 합', NOW(), NOW()),
       (22, 'combinatorics', '조합론', NOW(), NOW()),
       (23, 'bfs', '너비 우선 탐색', NOW(), NOW()),
       (24, 'case_work', '많은 조건 분기', NOW(), NOW()),
       (25, 'dfs', '깊이 우선 탐색', NOW(), NOW()),
       (26, 'shortest_path', '최단 경로', NOW(), NOW()),
       (27, 'bitmask', '비트마스킹', NOW(), NOW()),
       (28, 'hash_set', '해시를 사용한 집합과 맵', NOW(), NOW()),
       (29, 'dijkstra', '데이크스트라', NOW(), NOW()),
       (30, 'backtracking', '백트래킹', NOW(), NOW()),
       (31, 'sweeping', '스위핑', NOW(), NOW()),
       (32, 'disjoint_set', '분리 집합', NOW(), NOW()),
       (33, 'dp_tree', '트리에서의 다이나믹 프로그래밍', NOW(), NOW()),
       (34, 'tree_set', '트리를 사용한 집합과 맵', NOW(), NOW()),
       (35, 'parsing', '파싱', NOW(), NOW()),
       (36, 'priority_queue', '우선순위 큐', NOW(), NOW()),
       (37, 'divide_and_conquer', '분할 정복', NOW(), NOW()),
       (38, 'parametric_search', '매개 변수 탐색', NOW(), NOW()),
       (39, 'two_pointer', '두 포인터', NOW(), NOW()),
       (40, 'game_theory', '게임 이론', NOW(), NOW()),
       (41, 'stack', '스택', NOW(), NOW()),
       (42, 'probability', '확률론', NOW(), NOW()),
       (43, 'primality_test', '소수 판정', NOW(), NOW()),
       (44, 'flow', '최대 유량', NOW(), NOW()),
       (45, 'lazyprop', '느리게 갱신되는 세그먼트 트리', NOW(), NOW()),
       (46, 'dp_bitfield', '비트필드를 이용한 다이나믹 프로그래밍', NOW(), NOW()),
       (47, 'exponentiation_by_squaring', '분할 정복을 이용한 거듭제곱', NOW(), NOW()),
       (48, 'offline_queries', '오프라인 쿼리', NOW(), NOW()),
       (49, 'knapsack', '배낭 문제', NOW(), NOW()),
       (50, 'recursion', '재귀', NOW(), NOW()),
       (51, 'arbitrary_precision', '임의 정밀도 / 큰 수 연산', NOW(), NOW()),
       (52, 'dag', '방향 비순환 그래프', NOW(), NOW()),
       (53, 'coordinate_compression', '값 / 좌표 압축', NOW(), NOW()),
       (54, 'euclidean', '유클리드 호제법', NOW(), NOW()),
       (55, 'mst', '최소 스패닝 트리', NOW(), NOW()),
       (56, 'precomputation', '런타임 전의 전처리', NOW(), NOW()),
       (57, 'convex_hull', '볼록 껍질', NOW(), NOW()),
       (58, 'sieve', '에라토스테네스의 체', NOW(), NOW()),
       (59, 'topological_sorting', '위상 정렬', NOW(), NOW()),
       (60, 'linear_algebra', '선형대수학', NOW(), NOW()),
       (61, 'bipartite_matching', '이분 매칭', NOW(), NOW()),
       (62, 'inclusion_and_exclusion', '포함 배제의 원리', NOW(), NOW()),
       (63, 'lca', '최소 공통 조상', NOW(), NOW()),
       (64, 'hashing', '해싱', NOW(), NOW()),
       (65, 'floyd_warshall', '플로이드–워셜', NOW(), NOW()),
       (66, 'sparse_table', '희소 배열', NOW(), NOW()),
       (67, 'randomization', '무작위화', NOW(), NOW()),
       (68, 'scc', '강한 연결 요소', NOW(), NOW()),
       (69, 'grid_graph', '격자 그래프', NOW(), NOW()),
       (70, 'modular_multiplicative_inverse', '모듈로 곱셈 역원', NOW(), NOW()),
       (71, 'line_intersection', '선분 교차 판정', NOW(), NOW()),
       (72, 'smaller_to_larger', '작은 집합에서 큰 집합으로 합치는 테크닉', NOW(), NOW()),
       (73, 'fft', '고속 푸리에 변환', NOW(), NOW()),
       (74, 'trie', '트라이', NOW(), NOW()),
       (75, 'sqrt_decomposition', '제곱근 분할법', NOW(), NOW()),
       (76, 'deque', '덱', NOW(), NOW()),
       (77, 'calculus', '미적분학', NOW(), NOW()),
       (78, 'geometry_3d', '3차원 기하학', NOW(), NOW()),
       (79, 'ternary_search', '삼분 탐색', NOW(), NOW()),
       (80, 'heuristics', '휴리스틱', NOW(), NOW()),
       (81, 'mcmf', '최소 비용 최대 유량', NOW(), NOW()),
       (82, 'suffix_array', '접미사 배열과 LCP 배열', NOW(), NOW()),
       (83, 'sliding_window', '슬라이딩 윈도우', NOW(), NOW()),
       (84, 'traceback', '역추적', NOW(), NOW()),
       (85, 'sprague_grundy', '스프라그–그런디 정리', NOW(), NOW()),
       (86, 'cht', '볼록 껍질을 이용한 최적화', NOW(), NOW()),
       (87, 'euler_tour_technique', '오일러 경로 테크닉', NOW(), NOW()),
       (88, 'centroid', '센트로이드', NOW(), NOW()),
       (89, 'mitm', '중간에서 만나기', NOW(), NOW()),
       (90, 'bitset', '비트 집합', NOW(), NOW()),
       (91, 'pythagoras', '피타고라스 정리', NOW(), NOW()),
       (92, 'permutation_cycle_decomposition', '순열 사이클 분할', NOW(), NOW()),
       (93, 'kmp', 'KMP', NOW(), NOW()),
       (94, 'lis', '가장 긴 증가하는 부분 수열 문제', NOW(), NOW()),
       (95, 'gaussian_elimination', '가우스 소거법', NOW(), NOW()),
       (96, 'parity', '홀짝성', NOW(), NOW()),
       (97, 'hld', 'Heavy-light 분할', NOW(), NOW()),
       (98, 'polygon_area', '다각형의 넓이', NOW(), NOW()),
       (99, 'linearity_of_expectation', '기댓값의 선형성', NOW(), NOW()),
       (100, 'mfmc', '최대 유량 최소 컷 정리', NOW(), NOW()),
       (101, 'prime_factorization', '소인수분해', NOW(), NOW()),
       (102, 'centroid_decomposition', '센트로이드 분할', NOW(), NOW()),
       (103, 'bipartite_graph', '이분 그래프', NOW(), NOW()),
       (104, 'flt', '페르마의 소정리', NOW(), NOW()),
       (105, 'physics', '물리학', NOW(), NOW()),
       (106, 'eulerian_path', '오일러 경로', NOW(), NOW()),
       (107, '2_sat', '2-sat', NOW(), NOW()),
       (108, 'queue', '큐', NOW(), NOW()),
       (109, '0_1_bfs', '0-1 너비 우선 탐색', NOW(), NOW()),
       (110, 'articulation', '단절점과 단절선', NOW(), NOW()),
       (111, 'tsp', '외판원 순회 문제', NOW(), NOW()),
       (112, 'difference_array', '차분 배열 트릭', NOW(), NOW()),
       (113, 'flood_fill', '플러드 필', NOW(), NOW()),
       (114, 'pigeonhole_principle', '비둘기집 원리', NOW(), NOW()),
       (115, 'bcc', '이중 연결 요소', NOW(), NOW()),
       (116, 'pst', '퍼시스턴트 세그먼트 트리', NOW(), NOW()),
       (117, 'euler_phi', '오일러 피 함수', NOW(), NOW()),
       (118, 'planar_graph', '평면 그래프', NOW(), NOW()),
       (119, 'point_in_convex_polygon', '볼록 다각형 내부의 점 판정', NOW(), NOW()),
       (120, 'crt', '중국인의 나머지 정리', NOW(), NOW()),
       (121, 'deque_trick', '덱을 이용한 구간 최댓값 트릭', NOW(), NOW()),
       (122, 'linked_list', '연결 리스트', NOW(), NOW()),
       (123, 'functional_graph', '함수형 그래프', NOW(), NOW()),
       (124, 'cactus', '선인장', NOW(), NOW()),
       (125, 'bellman_ford', '벨만–포드', NOW(), NOW()),
       (126, 'dp_digit', '자릿수를 이용한 다이나믹 프로그래밍', NOW(), NOW()),
       (127, 'splay_tree', '스플레이 트리', NOW(), NOW()),
       (128, 'divide_and_conquer_optimization', '분할 정복을 사용한 최적화', NOW(), NOW()),
       (129, 'mo', 'mo''s', NOW(), NOW()),
       (130, 'extended_euclidean', '확장 유클리드 호제법', NOW(), NOW()),
       (131, 'rerooting', '트리에서의 전방향 다이나믹 프로그래밍', NOW(), NOW()),
       (132, 'half_plane_intersection', '반평면 교집합', NOW(), NOW()),
       (133, 'pbs', '병렬 이분 탐색', NOW(), NOW()),
       (134, 'generating_function', '생성 함수', NOW(), NOW()),
       (135, 'rotating_calipers', '회전하는 캘리퍼스', NOW(), NOW()),
       (136, 'euler_characteristic', '오일러 지표 (2, χ=V-E+F)', NOW(), NOW()),
       (137, 'regex', '정규 표현식', NOW(), NOW()),
       (138, 'aho_corasick', '아호-코라식', NOW(), NOW()),
       (139, 'slope_trick', '함수 개형을 이용한 최적화', NOW(), NOW()),
       (140, 'multi_segtree', '다차원 세그먼트 트리', NOW(), NOW()),
       (141, 'tree_diameter', '트리의 지름', NOW(), NOW()),
       (142, 'harmonic_number', '조화수', NOW(), NOW()),
       (143, 'dp_sum_over_subsets', '부분집합의 합 다이나믹 프로그래밍', NOW(), NOW()),
       (144, 'dp_deque', '덱을 이용한 다이나믹 프로그래밍', NOW(), NOW()),
       (145, 'manacher', '매내처', NOW(), NOW()),
       (146, 'invariant', '불변량 찾기', NOW(), NOW()),
       (147, 'miller_rabin', '밀러–라빈 소수 판별법', NOW(), NOW()),
       (148, 'mobius_inversion', '뫼비우스 반전 공식', NOW(), NOW()),
       (149, 'pollard_rho', '폴라드 로', NOW(), NOW()),
       (150, 'angle_sorting', '각도 정렬', NOW(), NOW()),
       (151, 'tree_isomorphism', '트리 동형 사상', NOW(), NOW()),
       (152, 'merge_sort_tree', '머지 소트 트리', NOW(), NOW()),
       (153, 'maximum_subarray', '최대 부분 배열 문제', NOW(), NOW()),
       (154, 'point_in_non_convex_polygon', '오목 다각형 내부의 점 판정', NOW(), NOW()),
       (155, 'simulated_annealing', '담금질 기법', NOW(), NOW()),
       (156, 'dp_connection_profile', '커넥션 프로파일을 이용한 다이나믹 프로그래밍', NOW(), NOW()),
       (157, 'lcs', '최장 공통 부분 수열 문제', NOW(), NOW()),
       (158, 'link_cut_tree', '링크/컷 트리', NOW(), NOW()),
       (159, 'berlekamp_massey', '벌리캠프–매시', NOW(), NOW()),
       (160, 'hall', '홀의 결혼 정리', NOW(), NOW()),
       (161, 'rabin_karp', '라빈–카프', NOW(), NOW()),
       (162, 'numerical_analysis', '수치해석', NOW(), NOW()),
       (163, 'statistics', '통계학', NOW(), NOW()),
       (164, 'offline_dynamic_connectivity', '오프라인 동적 연결성 판정', NOW(), NOW()),
       (165, 'z', 'z', NOW(), NOW()),
       (166, 'cartesian_tree', '데카르트 트리', NOW(), NOW()),
       (167, 'hungarian', '헝가리안', NOW(), NOW()),
       (168, 'tree_compression', '트리 압축', NOW(), NOW()),
       (169, 'alien', 'Aliens 트릭', NOW(), NOW()),
       (170, 'linear_programming', '선형 계획법', NOW(), NOW()),
       (171, 'geometric_boolean_operations', '도형에서의 불 연산', NOW(), NOW()),
       (172, 'lucas', '뤼카 정리', NOW(), NOW()),
       (173, 'voronoi', '보로노이 다이어그램', NOW(), NOW()),
       (174, 'circulation', '서큘레이션', NOW(), NOW()),
       (175, 'green', '그린 정리', NOW(), NOW()),
       (176, 'dual_graph', '쌍대 그래프', NOW(), NOW()),
       (177, 'beats', '세그먼트 트리 비츠', NOW(), NOW()),
       (178, 'duality', '쌍대성', NOW(), NOW()),
       (179, 'li_chao_tree', '리–차오 트리', NOW(), NOW()),
       (180, 'general_matching', '일반적인 매칭', NOW(), NOW()),
       (181, 'polynomial_interpolation', '다항식 보간법', NOW(), NOW()),
       (182, 'monotone_queue_optimization', '단조 큐를 이용한 최적화', NOW(), NOW()),
       (183, 'pick', '픽의 정리', NOW(), NOW()),
       (184, 'matroid', '매트로이드', NOW(), NOW()),
       (185, 'cdq', 'cdq 분할 정복', NOW(), NOW()),
       (186, 'kitamasa', '다항식을 이용한 선형점화식 계산', NOW(), NOW()),
       (187, 'xor_basis', '배타적 논리합 기저 (2, gf(2, 2))', NOW(), NOW()),
       (188, 'discrete_log', '이산 로그', NOW(), NOW()),
       (189, 'geometry_hyper', '4차원 이상의 기하학', NOW(), NOW()),
       (190, 'tree_decomposition', '트리 분할', NOW(), NOW()),
       (191, 'burnside', '번사이드 보조정리', NOW(), NOW()),
       (192, 'degree_sequence', '차수열', NOW(), NOW()),
       (193, 'min_enclosing_circle', '최소 외접원', NOW(), NOW()),
       (194, 'utf8', 'utf-8 입력 처리', NOW(), NOW()),
       (195, 'bulldozer', 'bulldozer 트릭', NOW(), NOW()),
       (196, 'suffix_tree', '접미사 트리', NOW(), NOW()),
       (197, 'bidirectional_search', '양방향 탐색', NOW(), NOW()),
       (198, 'differential_cryptanalysis', '차분 공격', NOW(), NOW()),
       (199, 'dominator_tree', '도미네이터 트리', NOW(), NOW()),
       (200, 'palindrome_tree', '회문 트리', NOW(), NOW()),
       (201, 'bayes', '베이즈 정리', NOW(), NOW()),
       (202, 'pisano', '피사노 주기', NOW(), NOW()),
       (203, 'knuth_x', '크누스 X', NOW(), NOW()),
       (204, 'top_tree', '탑 트리', NOW(), NOW()),
       (205, 'dancing_links', '춤추는 링크', NOW(), NOW()),
       (206, 'stable_marriage', '안정 결혼 문제', NOW(), NOW()),
       (207, 'lgv', '린드스트롬–게셀–비엔노 보조정리', NOW(), NOW()),
       (208, 'rope', '로프', NOW(), NOW()),
       (209, 'gradient_descent', '경사 하강법', NOW(), NOW()),
       (210, 'knuth', '크누스 최적화', NOW(), NOW()),
       (211, 'delaunay', '델로네 삼각분할', NOW(), NOW()),
       (212, 'floor_sum', '유리 등차수열의 내림 합', NOW(), NOW()),
       (213, 'bitset_lcs', '비트 집합을 이용한 최장 공통 부분 수열 최적화', NOW(), NOW()),
       (214, 'birthday', '생일 문제', NOW(), NOW()),
       (215, 'hirschberg', '히르쉬버그', NOW(), NOW()),
       (216, 'chordal_graph', '현 그래프', NOW(), NOW()),
       (217, 'discrete_sqrt', '이산 제곱근', NOW(), NOW()),
       (218, 'multipoint_evaluation', '다중 대입값 계산', NOW(), NOW()),
       (219, 'lte', '지수승강 보조정리', NOW(), NOW()),
       (220, 'directed_mst', '유향 최소 스패닝 트리', NOW(), NOW()),
       (221, 'stoer_wagner', '스토어–바그너', NOW(), NOW()),
       (222, 'hackenbush', '하켄부시 게임', NOW(), NOW()),
       (223, 'dial', '다이얼', NOW(), NOW()),
       (224, 'majority_vote', '보이어–무어 다수결 투표', NOW(), NOW()),
       (225, 'kinetic_segtree', '키네틱 세그먼트 트리', NOW(), NOW()),
       (226, 'rb_tree', '레드-블랙 트리', NOW(), NOW()),
       (227, 'a_star', 'a*', NOW(), NOW()),
       (228, 'treewidth', '제한된 트리 너비', NOW(), NOW()),
       (229, 'discrete_kth_root', '이산 k제곱근', NOW(), NOW());